In [4]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
import os
import sys
import pandas as pd
import matplotlib.pyplot as plt
import cobra

# Add parent directory to Python path
sys.path.append(os.path.abspath('..'))

# First, import the base kinGEMs package
import kinGEMs

# Import necessary functions from kinGEMs package
from kinGEMs.dataset import load_model, convert_to_irreversible, prepare_model_data, retrieve_sequences, map_metabolites, merge_substrate_sequences, process_merged_data_with_folds
from kinGEMs.modeling.optimize import run_optimization_with_dataframe
from kinGEMs.plots import plot_flux_distribution  # Assuming this function exists

# Define paths
data_dir = "../data"
raw_data_dir = os.path.join(data_dir, "raw")
model_path = os.path.join(raw_data_dir, "e_coli_core.xml")
interim_data_dir = os.path.join(data_dir, "interim")
processed_data_dir = os.path.join(data_dir, "processed")
CPIPred_data_dir = os.path.join(interim_data_dir, "CPI-Pred predictions")

# # Step 1: Load the model
# print("Loading model...")
# model = load_model(model_path)
# print(f"Model loaded with {len(model.reactions)} reactions and {len(model.metabolites)} metabolites")

# # Step 2: Convert to irreversible model
# print("Converting to irreversible model...")
# irrev_model = convert_to_irreversible(model)
# print(f"Irreversible model created with {len(irrev_model.reactions)} reactions")

# Step 1: Prepare model data (metabolite and sequence mapping)
print("Preparing model data...")
# Define output paths
substrates_output = os.path.join(interim_data_dir, "ecoli_substrates.csv")
sequences_output = os.path.join(interim_data_dir, "ecoli_sequences.csv")

# Prepare model data
irrev_model, substrate_df, sequences_df = prepare_model_data(
    model_path=model_path,
    substrates_output=substrates_output,
    sequences_output=sequences_output,
    organism='E coli'
)

display(substrate_df)
display(sequences_df)

# Step 2: Merge substrate and sequence data
print("Merging substrate and sequence data...")
merged_data_output = os.path.join(interim_data_dir, "ecoli_merged_data.csv")
merged_data = merge_substrate_sequences(
    substrate_df=substrate_df,
    sequences_df=sequences_df,
    model=irrev_model,
    output_path=merged_data_output
)

display(merged_data)

### DEBUGGED UP TO THIS POINT - CHECK WHERE CPI-PRED KCAT VALUES ARE INCORPORATED 


# Step 3: Create kcat data file from CPI-Pred fold predictions
print("Obtaining all kcat values for reactions from CPI-Pred...")
processed_data_output = os.path.join(processed_data_dir, "ecoli_proccesed_data.csv")
fold_csv_paths = [
    os.path.join(CPIPred_data_dir, f"ecoli_predictions_fold_{i}.csv") 
    for i in range(1, 6)
]
processed_data = process_merged_data_with_folds(
    merged_data=merged_data,
    fold_csv_paths=fold_csv_paths,
    output_path=processed_data_output
)

# Step 4: Run optimization
print("Running optimization...")
# Set parameters for optimization
biomass_reaction = 'BIOMASS_Ec_iML1515_core_75p37M'  # Update with your biomass reaction ID
enzyme_upper_bound = 0.125  # gP/gDCW, enzyme fraction upper bound

# Run optimization
solution, flux_distribution = run_optimization_with_dataframe(
    model=irrev_model,
    processed_df=processed_data,
    objective_reaction=biomass_reaction,
    enzyme_upper_bound=enzyme_upper_bound,
    enzyme_ratio=True  # Using enzyme fraction constraint,
    output_dir=
)

print(f"Optimization complete. Biomass flux: {solution.objective_value}")

# Step 5: Plot results
print("Plotting flux distribution...")
# Plot flux distribution
fig = plot_flux_distribution(flux_distribution)
plt.show()

# Save results
flux_distribution.to_csv(os.path.join(processed_data_dir, "e_coli_flux_distribution.csv"), index=False)

print("Pipeline completed successfully!")

Preparing model data...
Warning: Model has 8 validation errors
Loaded model with 95 reactions and 72 metabolites
Read LP format model from file C:\Users\Rana\AppData\Local\Temp\tmp_72aqswc.lp

2025-03-28 12:50:37,950 - gurobipy - INFO - Read LP format model from file C:\Users\Rana\AppData\Local\Temp\tmp_72aqswc.lp

Reading time = 0.01 seconds

2025-03-28 12:50:37,950 - gurobipy - INFO - Reading time = 0.01 seconds

: 72 rows, 190 columns, 720 nonzeros

2025-03-28 12:50:37,950 - gurobipy - INFO - : 72 rows, 190 columns, 720 nonzeros
2025-03-28 12:50:38,018 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,018 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,018 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,018 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,031 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,044 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,045 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,061 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,074 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,076 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,077 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,079 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,079 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,084 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,086 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,086 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,086 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,086 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,093 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,094 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,106 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,108 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,109 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,110 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,110 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,110 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,110 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,110 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,110 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,119 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,119 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,119 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,119 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,119 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,125 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,138 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,139 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,155 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,155 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,155 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,155 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.
2025-03-28 12:50:38,168 - cobra.medium.boundary_types - INFO - Compartment `e` sounds like an external compartment. Using this one without counting boundary reactions.

Number of reactions that are non-exchange:  75
Number of reactions that are exchange:  20
Number of reactions being added from non-exchange: 39
Number of reactions being added from exchange: 59
Converted to irreversible model with 154 reactions
Extracted 264 substrate-reaction pairs

c:\Users\Rana\OneDrive\Documents\GitHub\kinGEMs_v2\kinGEMs\dataset.py:214: DtypeWarning: Columns (4,10) have mixed types. Specify dtype option on import or set low_memory=False.
  SEED_comps = pd.read_csv(SEED_COMPOUNDS, sep='\t')
2025-03-28 12:50:49,360 - kinGEMs.dataset - INFO - There are 71 substrates in the GEM.
2025-03-28 12:50:49,393 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,393 - kinGEMs.dataset - INFO - Mapping substrate: atp_c
2025-03-28 12:50:49,424 - kinGEMs.dataset - INFO - BiGG Name: ATP C10H12N5O13P3
2025-03-28 12:50:49,471 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O)([O-])OP(=O)([O-])[O-])[C@@H](O)[C@H]1O
2025-03-28 12:50:49,471 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,471 - kinGEMs.dataset - INFO - Mapping substrate: f6p_c
2025-03-28 12:50:49,503 - kinGEMs.dataset - INFO - BiGG Name: D-Fructose 6-phosphate
2025-03-28 12:50:49,543 - kinGEMs.dataset - INFO - SMILES found in SEED: O=P([O-])([O-])OC[C@H]1O[C@](O)(CO)[C@@H](O)[C@@H]1O
2025-03-28 12:50:49,544 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,544 - kinGEMs.dataset - INFO - Mapping substrate: coa_c
2025-03-28 12:50:49,577 - kinGEMs.dataset - INFO - BiGG Name: Coenzyme A
2025-03-28 12:50:49,655 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,655 - kinGEMs.dataset - INFO - Mapping substrate: pyr_c
2025-03-28 12:50:49,699 - kinGEMs.dataset - INFO - BiGG Name: Pyruvate
2025-03-28 12:50:49,740 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: CC(=O)C(=O)[O-]
2025-03-28 12:50:49,740 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,740 - kinGEMs.dataset - INFO - Mapping substrate: g6p_c
2025-03-28 12:50:49,766 - kinGEMs.dataset - INFO - BiGG Name: D-Glucose 6-phosphate
2025-03-28 12:50:49,813 - kinGEMs.dataset - INFO - SMILES found in SEED: O=P([O-])([O-])OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O
2025-03-28 12:50:49,813 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,813 - kinGEMs.dataset - INFO - Mapping substrate: 3pg_c
2025-03-28 12:50:49,848 - kinGEMs.dataset - INFO - BiGG Name: 3-Phospho-D-glycerate
2025-03-28 12:50:49,891 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C([O-])[C@H](O)COP(=O)([O-])[O-]
2025-03-28 12:50:49,891 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,891 - kinGEMs.dataset - INFO - Mapping substrate: 6pgl_c
2025-03-28 12:50:49,922 - kinGEMs.dataset - INFO - BiGG Name: 6-phospho-D-glucono-1,5-lactone
2025-03-28 12:50:49,954 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C1O[C@H](COP(=O)([O-])[O-])[C@@H](O)[C@H](O)[C@H]1O
2025-03-28 12:50:49,954 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:49,954 - kinGEMs.dataset - INFO - Mapping substrate: h2o_c
2025-03-28 12:50:49,985 - kinGEMs.dataset - INFO - BiGG Name: H2O H2O
2025-03-28 12:50:50,051 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,051 - kinGEMs.dataset - INFO - Mapping substrate: acald_c
2025-03-28 12:50:50,078 - kinGEMs.dataset - INFO - BiGG Name: Acetaldehyde
2025-03-28 12:50:50,120 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: CC=O
2025-03-28 12:50:50,121 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,121 - kinGEMs.dataset - INFO - Mapping substrate: nad_c
2025-03-28 12:50:50,153 - kinGEMs.dataset - INFO - BiGG Name: Nicotinamide adenine dinucleotide
2025-03-28 12:50:50,188 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)c1
2025-03-28 12:50:50,188 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,188 - kinGEMs.dataset - INFO - Mapping substrate: akg_e
2025-03-28 12:50:50,224 - kinGEMs.dataset - INFO - BiGG Name: 2-Oxoglutarate
2025-03-28 12:50:50,262 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C([O-])CCC(=O)C(=O)[O-]
2025-03-28 12:50:50,262 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,263 - kinGEMs.dataset - INFO - Mapping substrate: h_e
2025-03-28 12:50:50,295 - kinGEMs.dataset - INFO - BiGG Name: H+
2025-03-28 12:50:50,335 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: [H+]
2025-03-28 12:50:50,336 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,336 - kinGEMs.dataset - INFO - Mapping substrate: 2pg_c
2025-03-28 12:50:50,361 - kinGEMs.dataset - INFO - BiGG Name: D-Glycerate 2-phosphate
2025-03-28 12:50:50,407 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C([O-])[C@@H](CO)OP(=O)([O-])[O-]
2025-03-28 12:50:50,408 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,408 - kinGEMs.dataset - INFO - Mapping substrate: pi_e
2025-03-28 12:50:50,440 - kinGEMs.dataset - INFO - BiGG Name: Phosphate
2025-03-28 12:50:50,479 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=P([O-])([O-])O
2025-03-28 12:50:50,480 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,481 - kinGEMs.dataset - INFO - Mapping substrate: etoh_c
2025-03-28 12:50:50,510 - kinGEMs.dataset - INFO - BiGG Name: Ethanol
2025-03-28 12:50:50,553 - kinGEMs.dataset - INFO - SMILES found in SEED: CCO
2025-03-28 12:50:50,554 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,554 - kinGEMs.dataset - INFO - Mapping substrate: acald_e
2025-03-28 12:50:50,577 - kinGEMs.dataset - INFO - BiGG Name: Acetaldehyde
2025-03-28 12:50:50,623 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: CC=O
2025-03-28 12:50:50,623 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,624 - kinGEMs.dataset - INFO - Mapping substrate: ac_c
2025-03-28 12:50:50,649 - kinGEMs.dataset - INFO - BiGG Name: Acetate
2025-03-28 12:50:50,684 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: CC(=O)[O-]
2025-03-28 12:50:50,684 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,684 - kinGEMs.dataset - INFO - Mapping substrate: co2_c
2025-03-28 12:50:50,727 - kinGEMs.dataset - INFO - BiGG Name: CO2 CO2
2025-03-28 12:50:50,765 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C=O
2025-03-28 12:50:50,766 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,766 - kinGEMs.dataset - INFO - Mapping substrate: pep_c
2025-03-28 12:50:50,797 - kinGEMs.dataset - INFO - BiGG Name: Phosphoenolpyruvate
2025-03-28 12:50:50,843 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: C=C(OP(=O)([O-])[O-])C(=O)[O-]
2025-03-28 12:50:50,843 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,843 - kinGEMs.dataset - INFO - Mapping substrate: cit_c
2025-03-28 12:50:50,867 - kinGEMs.dataset - INFO - BiGG Name: Citrate
2025-03-28 12:50:50,920 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C([O-])CC(O)(CC(=O)[O-])C(=O)[O-]
2025-03-28 12:50:50,921 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,921 - kinGEMs.dataset - INFO - Mapping substrate: acon_C_c
2025-03-28 12:50:50,950 - kinGEMs.dataset - INFO - BiGG Name: Cis-Aconitate
2025-03-28 12:50:50,989 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C([O-])/C=C(/CC(=O)[O-])C(=O)[O-]
2025-03-28 12:50:50,989 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:50,990 - kinGEMs.dataset - INFO - Mapping substrate: oaa_c
2025-03-28 12:50:51,020 - kinGEMs.dataset - INFO - BiGG Name: Oxaloacetate
2025-03-28 12:50:51,055 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C([O-])CC(=O)C(=O)[O-]
2025-03-28 12:50:51,055 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,055 - kinGEMs.dataset - INFO - Mapping substrate: ac_e
2025-03-28 12:50:51,095 - kinGEMs.dataset - INFO - BiGG Name: Acetate
2025-03-28 12:50:51,133 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: CC(=O)[O-]
2025-03-28 12:50:51,133 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,133 - kinGEMs.dataset - INFO - Mapping substrate: amp_c
2025-03-28 12:50:51,165 - kinGEMs.dataset - INFO - BiGG Name: AMP C10H12N5O7P
2025-03-28 12:50:51,227 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,227 - kinGEMs.dataset - INFO - Mapping substrate: akg_c
2025-03-28 12:50:51,262 - kinGEMs.dataset - INFO - BiGG Name: 2-Oxoglutarate
2025-03-28 12:50:51,296 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C([O-])CCC(=O)C(=O)[O-]
2025-03-28 12:50:51,296 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,296 - kinGEMs.dataset - INFO - Mapping substrate: adp_c
2025-03-28 12:50:51,333 - kinGEMs.dataset - INFO - BiGG Name: ADP C10H12N5O10P2
2025-03-28 12:50:51,372 - kinGEMs.dataset - INFO - SMILES found in SEED: Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O)([O-])O)[C@@H](O)[C@H]1O
2025-03-28 12:50:51,372 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,375 - kinGEMs.dataset - INFO - Mapping substrate: pi_c
2025-03-28 12:50:51,404 - kinGEMs.dataset - INFO - BiGG Name: Phosphate
2025-03-28 12:50:51,442 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=P([O-])([O-])O
2025-03-28 12:50:51,442 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,442 - kinGEMs.dataset - INFO - Mapping substrate: accoa_c
2025-03-28 12:50:51,470 - kinGEMs.dataset - INFO - BiGG Name: Acetyl-CoA
2025-03-28 12:50:51,512 - kinGEMs.dataset - INFO - SMILES found in SEED: CC(=O)SCCNC(=O)CCNC(=O)[C@H](O)C(C)(C)COP(=O)([O-])OP(=O)([O-])OC[C@H]1O[C@@H](n2cnc3c(N)ncnc32)[C@H](O)[C@@H]1OP(=O)([O-])[O-]
2025-03-28 12:50:51,513 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,513 - kinGEMs.dataset - INFO - Mapping substrate: h_c
2025-03-28 12:50:51,545 - kinGEMs.dataset - INFO - BiGG Name: H+
2025-03-28 12:50:51,577 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: [H+]
2025-03-28 12:50:51,577 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,577 - kinGEMs.dataset - INFO - Mapping substrate: e4p_c
2025-03-28 12:50:51,620 - kinGEMs.dataset - INFO - BiGG Name: D-Erythrose 4-phosphate
2025-03-28 12:50:51,659 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C[C@H](O)[C@H](O)COP(=O)([O-])[O-]
2025-03-28 12:50:51,661 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,661 - kinGEMs.dataset - INFO - Mapping substrate: g3p_c
2025-03-28 12:50:51,693 - kinGEMs.dataset - INFO - BiGG Name: Glyceraldehyde 3-phosphate
2025-03-28 12:50:51,733 - kinGEMs.dataset - INFO - SMILES found in SEED: O=CC(O)COP(=O)([O-])[O-]
2025-03-28 12:50:51,734 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,734 - kinGEMs.dataset - INFO - Mapping substrate: gln__L_c
2025-03-28 12:50:51,764 - kinGEMs.dataset - INFO - BiGG Name: L-Glutamine
2025-03-28 12:50:51,803 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: NC(=O)CC[C@H]([NH3+])C(=O)[O-]
2025-03-28 12:50:51,803 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,803 - kinGEMs.dataset - INFO - Mapping substrate: glu__L_c
2025-03-28 12:50:51,832 - kinGEMs.dataset - INFO - BiGG Name: L-Glutamate
2025-03-28 12:50:51,875 - kinGEMs.dataset - INFO - SMILES found in SEED: [NH3+]C(CCC(=O)[O-])C(=O)[O-]
2025-03-28 12:50:51,875 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,876 - kinGEMs.dataset - INFO - Mapping substrate: nadph_c
2025-03-28 12:50:51,903 - kinGEMs.dataset - INFO - BiGG Name: Nicotinamide adenine dinucleotide phosphate - reduced
2025-03-28 12:50:51,942 - kinGEMs.dataset - INFO - SMILES found in SEED: NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1
2025-03-28 12:50:51,942 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:51,942 - kinGEMs.dataset - INFO - Mapping substrate: r5p_c
2025-03-28 12:50:51,978 - kinGEMs.dataset - INFO - BiGG Name: Alpha-D-Ribose 5-phosphate
2025-03-28 12:50:52,014 - kinGEMs.dataset - INFO - SMILES found in SEED: O=P([O-])([O-])OC[C@H]1O[C@H](O)[C@H](O)[C@@H]1O
2025-03-28 12:50:52,014 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,014 - kinGEMs.dataset - INFO - Mapping substrate: pyr_e
2025-03-28 12:50:52,053 - kinGEMs.dataset - INFO - BiGG Name: Pyruvate
2025-03-28 12:50:52,091 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: CC(=O)C(=O)[O-]
2025-03-28 12:50:52,092 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,092 - kinGEMs.dataset - INFO - Mapping substrate: co2_e
2025-03-28 12:50:52,123 - kinGEMs.dataset - INFO - BiGG Name: CO2 CO2
2025-03-28 12:50:52,161 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C=O
2025-03-28 12:50:52,161 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,161 - kinGEMs.dataset - INFO - Mapping substrate: ru5p__D_c
2025-03-28 12:50:52,187 - kinGEMs.dataset - INFO - BiGG Name: D-Ribulose 5-phosphate
2025-03-28 12:50:52,228 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C(CO)[C@H](O)[C@H](O)COP(=O)([O-])[O-]
2025-03-28 12:50:52,229 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,229 - kinGEMs.dataset - INFO - Mapping substrate: succ_e
2025-03-28 12:50:52,257 - kinGEMs.dataset - INFO - BiGG Name: Succinate
2025-03-28 12:50:52,297 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C([O-])CCC(=O)[O-]
2025-03-28 12:50:52,298 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,298 - kinGEMs.dataset - INFO - Mapping substrate: o2_c
2025-03-28 12:50:52,327 - kinGEMs.dataset - INFO - BiGG Name: O2 O2
2025-03-28 12:50:52,368 - kinGEMs.dataset - INFO - SMILES found in SEED: O=O
2025-03-28 12:50:52,368 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,368 - kinGEMs.dataset - INFO - Mapping substrate: q8h2_c
2025-03-28 12:50:52,390 - kinGEMs.dataset - INFO - BiGG Name: Ubiquinol-8
2025-03-28 12:50:52,436 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: COc1c(O)c(C)c(C/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CCC=C(C)C)c(O)c1OC
2025-03-28 12:50:52,436 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,439 - kinGEMs.dataset - INFO - Mapping substrate: lac__D_e
2025-03-28 12:50:52,452 - kinGEMs.dataset - INFO - BiGG Name: D-Lactate
2025-03-28 12:50:52,505 - kinGEMs.dataset - INFO - SMILES found in SEED: C[C@@H](O)C(=O)[O-]
2025-03-28 12:50:52,506 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,506 - kinGEMs.dataset - INFO - Mapping substrate: succ_c
2025-03-28 12:50:52,531 - kinGEMs.dataset - INFO - BiGG Name: Succinate
2025-03-28 12:50:52,576 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C([O-])CCC(=O)[O-]
2025-03-28 12:50:52,577 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,577 - kinGEMs.dataset - INFO - Mapping substrate: etoh_e
2025-03-28 12:50:52,606 - kinGEMs.dataset - INFO - BiGG Name: Ethanol
2025-03-28 12:50:52,646 - kinGEMs.dataset - INFO - SMILES found in SEED: CCO
2025-03-28 12:50:52,647 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,647 - kinGEMs.dataset - INFO - Mapping substrate: q8_c
2025-03-28 12:50:52,669 - kinGEMs.dataset - INFO - BiGG Name: Ubiquinone-8
2025-03-28 12:50:52,704 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: COC1=C(OC)C(=O)C(C/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CC/C=C(\C)CCC=C(C)C)=C(C)C1=O
2025-03-28 12:50:52,704 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,704 - kinGEMs.dataset - INFO - Mapping substrate: s7p_c
2025-03-28 12:50:52,744 - kinGEMs.dataset - INFO - BiGG Name: Sedoheptulose 7-phosphate
2025-03-28 12:50:52,788 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C(CO)[C@@H](O)[C@H](O)[C@H](O)[C@H](O)COP(=O)([O-])[O-]
2025-03-28 12:50:52,789 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,789 - kinGEMs.dataset - INFO - Mapping substrate: nadh_c
2025-03-28 12:50:52,809 - kinGEMs.dataset - INFO - BiGG Name: Nicotinamide adenine dinucleotide - reduced
2025-03-28 12:50:52,856 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](O)[C@@H]3O)[C@@H](O)[C@H]2O)C=CC1
2025-03-28 12:50:52,858 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,858 - kinGEMs.dataset - INFO - Mapping substrate: nadp_c
2025-03-28 12:50:52,888 - kinGEMs.dataset - INFO - BiGG Name: Nicotinamide adenine dinucleotide phosphate
2025-03-28 12:50:52,928 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: NC(=O)c1ccc[n+]([C@@H]2O[C@H](COP(=O)([O-])OP(=O)([O-])OC[C@H]3O[C@@H](n4cnc5c(N)ncnc54)[C@H](OP(=O)([O-])[O-])[C@@H]3O)[C@@H](O)[C@H]2O)c1
2025-03-28 12:50:52,929 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,929 - kinGEMs.dataset - INFO - Mapping substrate: xu5p__D_c
2025-03-28 12:50:52,954 - kinGEMs.dataset - INFO - BiGG Name: D-Xylulose 5-phosphate
2025-03-28 12:50:52,983 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C(CO)[C@@H](O)[C@H](O)COP(=O)([O-])[O-]
2025-03-28 12:50:52,983 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:52,983 - kinGEMs.dataset - INFO - Mapping substrate: dhap_c
2025-03-28 12:50:53,017 - kinGEMs.dataset - INFO - BiGG Name: Dihydroxyacetone phosphate
2025-03-28 12:50:53,063 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C(CO)COP(=O)([O-])[O-]
2025-03-28 12:50:53,064 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,065 - kinGEMs.dataset - INFO - Mapping substrate: for_e
2025-03-28 12:50:53,096 - kinGEMs.dataset - INFO - BiGG Name: Formate
2025-03-28 12:50:53,135 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: O=C[O-]
2025-03-28 12:50:53,137 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,137 - kinGEMs.dataset - INFO - Mapping substrate: fru_e
2025-03-28 12:50:53,168 - kinGEMs.dataset - INFO - BiGG Name: D-Fructose
2025-03-28 12:50:53,204 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C(CO)[C@@H](O)[C@H](O)[C@H](O)CO
2025-03-28 12:50:53,204 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,204 - kinGEMs.dataset - INFO - Mapping substrate: fum_e
2025-03-28 12:50:53,231 - kinGEMs.dataset - INFO - BiGG Name: Fumarate
2025-03-28 12:50:53,280 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C([O-])/C=C/C(=O)[O-]
2025-03-28 12:50:53,280 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,280 - kinGEMs.dataset - INFO - Mapping substrate: glc__D_e
2025-03-28 12:50:53,298 - kinGEMs.dataset - INFO - BiGG Name: D-Glucose
2025-03-28 12:50:53,351 - kinGEMs.dataset - INFO - SMILES found in SEED: O=C[C@H](O)[C@@H](O)[C@H](O)[C@H](O)CO
2025-03-28 12:50:53,351 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,351 - kinGEMs.dataset - INFO - Mapping substrate: gln__L_e
2025-03-28 12:50:53,377 - kinGEMs.dataset - INFO - BiGG Name: L-Glutamine
2025-03-28 12:50:53,417 - kinGEMs.dataset - INFO - SMILES found in MetaNetX: NC(=O)CC[C@H]([NH3+])C(=O)[O-]
2025-03-28 12:50:53,417 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,418 - kinGEMs.dataset - INFO - Mapping substrate: glu__L_e
2025-03-28 12:50:53,444 - kinGEMs.dataset - INFO - BiGG Name: L-Glutamate
2025-03-28 12:50:53,488 - kinGEMs.dataset - INFO - SMILES found in SEED: [NH3+]C(CCC(=O)[O-])C(=O)[O-]
2025-03-28 12:50:53,488 - kinGEMs.dataset - INFO - -----------------------------
2025-03-28 12:50:53,489 - kinGEMs.dataset - INFO - Mapping substrate: h2o_e
2025-03-28 12:50:53,519 - kinGEMs.dataset - INFO - BiGG Name: H2O H2O
2025-03-28 12:50:53,578 - kinGEMs.dataset - INFO - -----------------------------

Mapped metabolites to SMILES (264 found)

2025-03-28 12:50:58,703 - root - WARNING - No sequence found for gene s0001

Retrieved 136 protein sequences

,Reaction,Substrate partner,SMILES,BiGG Name,DB Name,Cleaned Substrate
0,PFK,atp_c,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O...,ATP C10H12N5O13P3,ATP,atp
1,PFK,f6p_c,O=P([O-])([O-])OC[C@H]1O[C@](O)(CO)[C@@H](O)[C...,D-Fructose 6-phosphate,beta-D-Fructose 6-phosphate,f6p
2,PFL,coa_c,CC(C)(CO[P](O)(=O)O[P](O)(=O)OC[C@H]1O[C@H]([C...,Coenzyme A,NaN,coa
3,PFL,pyr_c,CC(=O)C(=O)[O-],Pyruvate,pyruvate,pyr
4,PGI,g6p_c,O=P([O-])([O-])OC[C@H]1OC(O)[C@H](O)[C@@H](O)[...,D-Glucose 6-phosphate,D-glucose-6-phosphate,g6p
...,...,...,...,...,...,...
259,MDH_reverse,h_c,[H+],H+,H(+),h
260,MDH_reverse,nadh_c,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,Nicotinamide adenine dinucleotide - reduced,NADH,nadh
261,MDH_reverse,oaa_c,O=C([O-])CC(=O)C(=O)[O-],Oxaloacetate,oxaloacetate,oaa
262,NH4t_reverse,nh4_c,[NH4+],Ammonium,NH4+,nh4
263,O2t_reverse,o2_c,O=O,O2 O2,O2,o2

    Single_gene   Name                                           Sequence
0         b1241   adhE  MAVTNVAELNALVERVKKAQREYASFTQEQVDKIFRAAALAAADAR...
1         b0351   mhpF  MSKRKVAIIGSGNIGTDLMIKILRHGQHLEMAVMVGIDPQSDGLAR...
2         s0001  s0001                                               None
3         b1849   purT  MTLLGTALRPAATRVMLLGSGELGKEVAIECQRLGVEVIAVDRYAD...
4         b3115   tdcD  MNEFPVVLVINCGSSSIKFSVLDASDCEVLMSGIADGINSENAFLS...
..          ...    ...                                                ...
132       b0008   talB  MTDKLTSLRQYTTVVADTGDIAAMKLYQPQDATTNPSLILNAAQIP...
133       b2464   talA  MNELDGIKQFTTVVADSGDIESIRHYHPQDATTNPSLLLKAAGLSQ...
134       b2465   tktB  MSRKDLANAIRALSMDAVQKANSGHPGAPMGMADIAEVLWNDFLKH...
135       b2935   tktA  MSSRKELANAIRALSMDAVQKAKSGHPGAPMGMADIAEVLWRDFLK...
136       b3919   tpiA  MRHPLVMGNWKLNGSRHMVHELVSNLRKELAGVAGCAVAIAPPEMY...

[137 rows x 3 columns]

Merging substrate and sequence data...

,Reactions,Reaction_partners,SMILES,BiGG Name,DB Name,Cleaned Substrate,Single_gene,GPR_rules,SEQ
0,PFK,atp_c,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O...,ATP C10H12N5O13P3,ATP,atp,b3916,b3916 or b1723,MIKKIGVLTSGGDAPGMNAAIRGVVRSALTEGLEVMGIYDGYLGLY...
1,PFK,atp_c,Nc1ncnc2c1ncn2[C@@H]1O[C@H](COP(=O)([O-])OP(=O...,ATP C10H12N5O13P3,ATP,atp,b1723,b3916 or b1723,MVRIYTLTLAPSLDSATITPQIYPEGKLRCTAPVFEPGGGGINVAR...
2,PFK,f6p_c,O=P([O-])([O-])OC[C@H]1O[C@](O)(CO)[C@@H](O)[C...,D-Fructose 6-phosphate,beta-D-Fructose 6-phosphate,f6p,b3916,b3916 or b1723,MIKKIGVLTSGGDAPGMNAAIRGVVRSALTEGLEVMGIYDGYLGLY...
3,PFK,f6p_c,O=P([O-])([O-])OC[C@H]1O[C@](O)(CO)[C@@H](O)[C...,D-Fructose 6-phosphate,beta-D-Fructose 6-phosphate,f6p,b1723,b3916 or b1723,MVRIYTLTLAPSLDSATITPQIYPEGKLRCTAPVFEPGGGGINVAR...
4,PFL,coa_c,CC(C)(CO[P](O)(=O)O[P](O)(=O)OC[C@H]1O[C@H]([C...,Coenzyme A,NaN,coa,b0902,((b0902 and b0903) and b2579) or (b0902 and b0...,MSVIGRIHSFESCGTVDGPGIRFITFFQGCLMRCLYCHNRDTWDTH...
...,...,...,...,...,...,...,...,...,...
598,MDH_reverse,nadh_c,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,Nicotinamide adenine dinucleotide - reduced,NADH,nadh,b3236,b3236,MKVAVLGAAGGIGQALALLLKTQLPSGSELSLYDIAPVTPGVAVDL...
599,MDH_reverse,oaa_c,O=C([O-])CC(=O)C(=O)[O-],Oxaloacetate,oxaloacetate,oaa,b3236,b3236,MKVAVLGAAGGIGQALALLLKTQLPSGSELSLYDIAPVTPGVAVDL...
600,NH4t_reverse,nh4_c,[NH4+],Ammonium,NH4+,nh4,s0001,s0001 or b0451,None
601,NH4t_reverse,nh4_c,[NH4+],Ammonium,NH4+,nh4,b0451,s0001 or b0451,MKIATIKTGLASLAMLPGLVMAAPAVADKADNAFMMICTALVLFMT...
602,O2t_reverse,o2_c,O=O,O2 O2,O2,o2,s0001,s0001,None

Running optimization...

KeyError: "Index 'BIOMASS_Ec_iML1515_core_75p37M' is not valid for indexed component 'reaction'"